### ISSUE TITLE
Ketika login admin 

### ISSUE THREAD

**Issue by munajatibnu** [abydahana/Aksara#1]
Error Number: 42000/1055

Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'aksara.app__activity_logs.ip_address' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SELECT `ip_address`, `browser`, `platform`, `timestamp`, DATE(timestamp) AS date FROM `app__activity_logs` WHERE `timestamp` >= '2020-12-12 14:16:18' GROUP BY `user_id`, `date`

Filename: F:/Ampps/www/aksara/vendor/codeigniter/system/database/DB_driver.php

Line Number: 691

**Comment by abydahana** [comment]
Halo, terkait error nonagregat pada query GROUP BY, belum ada cara terbaik yang saya temukan untuk mengatasinya karena beberapa alasan berikut:
1. Query berjalan dengan menambahkan primary (id) pada GROUP BY untuk tabel `app__activity_logs`, akan tetapi result yang ditampilkan tidak sesuai dengan ekspektasi yang mengharuskan grouping hanya berdasar `user_id` dan `date`;
2. Alasan lain yang sedang dalam pengkajian.

Untuk mengatasi permasalahan tersebut, sebagian besar artikel merekomendasikan untuk mengubah konfigurasi MySQL. Yaitu dengan menambahkan baris untuk mengubah sql_mode pada file `my.cnf` sesuai parameter berikut:
`[mysqld]`
`sql_mode = "STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION"`
kemudian restart service mysql.

Silakan merujuk pada artikel https://afrijaldzuhri.com/mengatasi-error-group-by-di-mysql/ atau https://www.google.com/search?safe=strict&rlz=1C1OKWM_enID888ID888&sxsrf=ALeKk0106RepWLE9JS5Tgd9R46Ry2PugeA%3A1608372337732&ei=cdDdX7ydLM62rQHJs7WYBQ&q=site%3Astackoverflow.com+Expression+%231+of+SELECT+list+is+not+in+GROUP+BY+clause+and+contains+nonaggregated+column+*%3B+this+is+incompatible+with+sql_mode%3Donly_full_group_by&oq=site%3Astackoverflow.com+Expression+%231+of+SELECT+list+is+not+in+GROUP+BY+clause+and+contains+nonaggregated+column+*%3B+this+is+incompatible+with+sql_mode%3Donly_full_group_by&gs_lcp=CgZwc3ktYWIQAzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQR1CtzElY3Z5KYKOhSmgAcAR4AIABAIgBAJIBAJgBA6ABAaoBB2d3cy13aXrIAQjAAQE&sclient=psy-ab&ved=0ahUKEwj8me3u5dntAhVOWysKHclZDVMQ4dUDCAw&uact=5

**Comment by munajatibnu** [comment]
sebagai informasi sy menggunakan ampps dan ketika di tambahkan baris code tersebut mysql nya tidak bisa berjalan

**Comment by abydahana** [comment]
Mungkin bisa dicoba dengan metode lain dengan cara menjalankan perintah ini dari dari pma atau sql manager favoritnya:

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

**Comment by munajatibnu** [comment]
terima kasih. masalah sudah bisa di atasi dengan cara ini SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

**Comment by abydahana** [comment]
Siap. Issue saya close, ya...
