### ISSUE TITLE
Multilingual menu

### ISSUE THREAD

**Issue by coolrix** [abydahana/aksara#124]
Hi about multilingual menus:
Your answer:
_Hello, thanks for using Aksara. You don’t need to create multiple menu for each language. The menu label will automatically generate the phrase itself. You can translate the phrase through the “Translations” instead.

But: I made a page in 3 different languages ( pages/about-us).  The system takes always the English one, even if I change the language

**Comment by abydahana** [comment]
Hello @coolrix, thanks for submitting new issue. About your question, we made a changes recently to add the multilingual support for the "Pages" module. To add the multilingual page, you must sets the **Page Slug** for each multilingual page identically.

For example:
#### English ####
Page Title: About Us
Page Slug: **about-us**
Language: English (Default)

#### Bahasa Indonesia ####
Page Title: Tentang Kami
Page Slug: **about-us**
Language: Bahasa Indonesia

Please update your Aksara version or make any changes for the following files listed under the recent commit: #125

**Comment by coolrix** [comment]
It works fine now

**Comment by abydahana** [comment]
Glad to know. I hope Aksara will meet with your project. Happy coding!
