### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by gosymbian** [abydahana/aksara#126]
Hi,

it seems that your site (aksaracms.com) is down ! can you check please; and where to get documentation ? it seems that this project is great.

Sincerly,
Domi.

**Comment by abydahana** [comment]
Hello, I just checked the site and it seems working fine. You can get the documentation on the site but it’s not yet fully documented (on going and still waiting community to help to improve).

You can still using the Aksara GitHub Issue if you have any questions.
