### ISSUE TITLE
Module Download File

### ISSUE THREAD

**Issue by anjarpinem** [abydahana/aksara#143]
Mas, apakah di cms ini tersedia untuk modul upload/download file? apakah boleh dibagikan jika ada?

**Comment by abydahana** [comment]
Bisa dibuat modulnya saja, set fieldnya sebagai file (single) atau files (multiple).

Contoh:
```$this->set_field('berkas', 'files');```

Nanti sudah otomatis terbentuk baik untuk formulir atau viewnya.

Atau jika ingin mengakses URL file bisa dipanggil dengan get_file('berkas', $source).

Parameter "berkas" adalah lokasi folder upload targetnya. Bisa disesuaikan dengan menggunakan ```$this->set_upload_path('nama_folder');```

Semoga bisa membantu.

**Comment by anjarpinem** [comment]
Terimakasih mas..

Oh iya mas, ada panduan saat menambahkan hak akses untuk, kenapa ya selalu muncul "Anda tidak mempunyai perizinan yang cukup untuk mengakses halaman yang diminta", padahal sudah kita checklist untuk group Super User/Global Administrator.

**Comment by abydahana** [comment]
Ada beberapa kemungkinan.
Kemungkinan pertama,  pada modul telah ditambahkan ```set_permission()``` tapi method atau submodul yang diakses tidak ditemukan;
Kemungkinan kedua adalah belum diberikannya hak akses untuk grup tersebut.

Setiap method atau modul yang dibuat akan otomatis terbuat hak aksesnya, atau bisa ditambahkan atau dihapus pada pengelolaan hak akses, yang kemudian dapat disesuaikan pada manajemen grup pengguna (checklist hak akses).

Harap cantumkan snippet untuk modul yang telah dibuat untuk kita bedah bersama 🙂
