### ISSUE TITLE
error after automatic update

### ISSUE THREAD

**Issue by coolrix** [abydahana/aksara#151]
After the last automatic update, i've the following error (500 error on website www.belgaphil.org).
I executed also composer.....

ERROR - 2022-04-11 12:12:48 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(255),
	MODIFY `hostname` varchar(255),
	MODIFY `port` int(5),
	MODIFY `usern...' at line 3
ERROR - 2022-04-11 12:12:48 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(255),
	MODIFY `port` int(5),
	MODIFY `username` varchar(512),
	MODIFY `passw...' at line 4
ERROR - 2022-04-11 12:12:48 --> Duplicate column name 'login_attempt'
ERROR - 2022-04-11 12:12:48 --> Unknown column 'country' in 'app__users'
ERROR - 2022-04-11 12:12:48 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UNSIGNED,
	MODIFY `status` tinyint DEFAULT 0' at line 4

**Comment by abydahana** [comment]
Hello, thanks for reporting. I will check it soon.

**Comment by abydahana** [comment]
Must be fixed since current update #418
