### ISSUE TITLE
Contoh Modul pada Addons Market

### ISSUE THREAD

**Issue by bangil0** [abydahana/aksara#179]
apakah contoh modul pada Addons Market seperti Modul Micro Forum tidak bisa di install pada aksara versi terbaru ?
**The Module Package Is Not Compatible With Your Current Aksara Version"**

**Comment by abydahana** [comment]
Saat ini belum ada pengembangan versi terkait tema dan modul pada sample addon yang tersedia. Untuk mencoba kompatibilitas, bisa mengunduh contoh addon, lalu mengubah kompatibilitas pada file package.json dari paket yang diunduh dan tambahkan versi Aksara terbaru pada parameter kompatibilitas.

**Comment by bangil0** [comment]
> Saat ini belum ada pengembangan versi terkait tema dan modul pada sample addon yang tersedia. Untuk mencoba kompatibilitas, bisa mengunduh contoh addon, lalu mengubah kompatibilitas pada file package.json dari paket yang diunduh dan tambahkan versi Aksara terbaru pada parameter kompatibilitas.

siap dicoba dan terima kasih

**Comment by abydahana** [comment]
Apakah informasinya sudah cukup membantu? Jika sudah saya izin close issue, ya...

**Comment by bangil0** [comment]
> Saat ini belum ada pengembangan versi terkait tema dan modul pada sample addon yang tersedia. Untuk mencoba kompatibilitas, bisa mengunduh contoh addon, lalu mengubah kompatibilitas pada file package.json dari paket yang diunduh dan tambahkan versi Aksara terbaru pada parameter kompatibilitas.

setelah saya ubah parameter kompatibilitas addons modul berhasil diinstall tp tidak berjalan dengan baik pada saat implementasi, contoh addons modul forum micro 
install sukses pada [AKSARA 4.3.24.1.9]

- [ v ]  tambah category sukse 

- [ v ] tambah topic sukses

- [ x ]  reply topic pada forum gagal muncul pesan "Uncaught Error: Syntax error, unrecognized expression: [data-segmentation=forum_topics|test_forum]"

apakah ada pengaturan lagi untuk penggunaan addons

**Comment by abydahana** [comment]
Terkait data segmentation sudah dilakukan commit untuk repo, tapi belum dilakukan compile version. Instalasi menggunakan composer mungkin belum mendapatkan source terbaru dari repository sampai ada peningkatan versi pada package untuk source terbaru.

**Comment by bangil0** [comment]
> Terkait data segmentation sudah dilakukan commit untuk repo, tapi belum dilakukan compile version. Instalasi menggunakan composer mungkin belum mendapatkan source terbaru dari repository sampai ada peningkatan versi pada package untuk source terbaru.

modul forum dicoba pada [Aksara Epsilon R3] versi zip rilis, terdapat error yang sama
