### ISSUE TITLE
Apakah projek ini akan terus dimaintain?

### ISSUE THREAD

**Issue by handoyo** [abydahana/aksara#209]
Sebelumnya terima kasih atas aplikasi CMS nya mas. tampilan admin panelnya keren.

Saya ingin tanya apakah aplikasi ini akan terus dimaintain?

Saya ingin memakai aplikasi ini untuk keperluan saya, karna aplikasi ini sudah support REST Api secara default. Top markotop.

Hanya saya khawatirnya tiba2 ga dimaintain lagi, ganti framework atau yang lainnya nanti jadi pusing. 😅 

Oya, apakah mungkin menghilangkan /public dari URL nya?

Makasih.

**Comment by abydahana** [comment]
Halo, proyek akan terus dimaintain. Saya sedang kembangkan versi supaya lebih mudah dalam custom add-on baik tema ataupun modul dan menghilangkan beberapa dependency yang sebelumnya bergantung pada core assets supaya mudah diaplikasikan dalam framework UI yang berbeda (tidak bergantung pada Bootstrap).

Silakan digunakan dengan nyaman dan tidak perlu khawatir dengan pengembangan jangka panjang.

Untuk menghilangkan path `public` bisa dengan melakukan pointing domain atau subdomain supaya langsung menuju ke folder `/public`, atau dengan memindahkan beberapa file ke root path dan mengubah beberapa konfigurasi path. Tapi saya sangat tidak sarankan untuk pemindahan file karena selain berkaitan dengan security, juga akan berpengaruh pada saat ada update. Sebagai gantinya, saya sedang uji coba tweak pada `htaccess` atau konfigurasi virtual host supaya bekerja multiplatform.

Ditunggu, ya...

**Comment by handoyo** [comment]
Terima kasih banyak atas informasinya. Saya akan tunggu versi dimana supaya /public nya bisa dihilangkan.

Oya, apakah mas nya punya tutorial membuat tema nya?

Saat ini saya sedang coba buat custom addon nya. nonton di youtube sambil test and trial juga.

**Comment by handoyo** [comment]
Maaf mas, mau nanya lagi.

Saya ingin bisa set multilevel kategori. Bagaimana caranya set di controller atau buat relasinya ya?

Jadi misalkan:

Kategori A
-Kategori B
--Kategori C
-Kategori D
Kategori E
-Kategori F

Makasih mas.

**Comment by abydahana** [comment]
> Terima kasih banyak atas informasinya. Saya akan tunggu versi dimana supaya /public nya bisa dihilangkan.
> 
> Oya, apakah mas nya punya tutorial membuat tema nya?
> 
> Saat ini saya sedang coba buat custom addon nya. nonton di youtube sambil test and trial juga.

Tema dan modul belum saya buat tutorialnya. Tapi sudah ada sample di market add-on.



> Maaf mas, mau nanya lagi.
> 
> Saya ingin bisa set multilevel kategori. Bagaimana caranya set di controller atau buat relasinya ya?
> 
> Jadi misalkan:
> 
> Kategori A -Kategori B --Kategori C -Kategori D Kategori E -Kategori F
> 
> Makasih mas.

Pengkategorian ini dalam bentuk dependent dropdown kah? Saya biasa gunakan grouping pada dropdown daripada dependent, atau membuatnya menjadi pilihan pada masing-masing modul.

Misalnya untuk dropdown:
Kategori A - Sub Kategori A1
Kategori A - Sub Kategori A3
Kategori B - Sub Kategori B1
Kategori B - Sub Kategori B2

Sedangkan struktur untuk modul:
Produk/Controllers/Produk.php
Produk/Controllers/Kategori.php
Produk/Controllers/Sub_kategori.php
Di mana sebelum masuk Produk.php, ada halaman untuk memilih kategori dan sub kategori terlebih dahulu.

**Comment by handoyo** [comment]
Saya sudah download contoh forum dan tema, Saya sudah install tema namun ketika test buka blog ada error gitu. saya jadinya pakai tema default lagi.

Untuk pengkategorian jadi seperti untuk toko online gitu mas. Jadi pas bikin kategori, kita bisa milih apakah kategori ini memiliki kategori diatasnya. Kalau ya berarti dia jadi sub kategori.

**Comment by handoyo** [comment]
Oya mas,

Saya lagi coba Rest API nya. Saya bisa mendapatkan access token lewat debug tools nya aksara seperti ini:

![image](https://user-images.githubusercontent.com/225439/176647734-26445848-6efc-4bb1-9f07-71900ed7aed6.png)

 
Namun ketika coba pakai postman, saya mendapatkan:

![image](https://user-images.githubusercontent.com/225439/176647865-6e3433a0-d152-4b4f-b704-98053faff50d.png)

![image](https://user-images.githubusercontent.com/225439/176648431-0a96aeb4-ae19-4288-ba29-1f062770589a.png)

Kira-kira apa yang salah ya?

**Comment by abydahana** [comment]
Response access_token digunakan untuk initialize request ke halaman restricted (yang perlu login) dengan menyertakan di header key x-access-token.

**Comment by handoyo** [comment]
Saya tidak mendapatkan response access_token ketika saya coba hit /public/auth lewat postman mas.

**Comment by abydahana** [comment]
Simulasinya seperti ini:
Pertama login dulu dengan postmannya, request dengan method POST dan berikan username dan password pada form data (body), nanti akan dapet response access_token jika login success. Response access_token tersebut yang digunakan untuk request berikutnya.

**Comment by handoyo** [comment]
POST nya ke public/auth kah mas atau ke URL mana untuk dapat access tokennya?

**Comment by abydahana** [comment]
> POST nya ke public/auth kah mas atau ke URL mana untuk dapat access tokennya?

Iya betul ke situ.

Setiap path bisa saja sama, tapi responsenya bisa berbeda tergantung methodnya. Contohnya pada request ke /create, /update, jika method POST maka akan mengirim data, sedangkan method GET akan mengambil data yang akan diupdate atau sampling input dari form add.

Khusus untuk path /delete hanya bisa menggunakan method DELETE.

**Comment by handoyo** [comment]
Maaf mas, saya sudah coba POST ke public/auth lewat postman namun saya tidak mendapatkan access token, melainkan seperti ini:

![image](https://user-images.githubusercontent.com/225439/176991988-897e1035-fcfc-44e1-b2d2-a1f6c1a8ec66.png)

**Comment by abydahana** [comment]
> Maaf mas, saya sudah coba POST ke public/auth lewat postman namun saya tidak mendapatkan access token, melainkan seperti ini:
> 
> ![image](https://user-images.githubusercontent.com/225439/176991988-897e1035-fcfc-44e1-b2d2-a1f6c1a8ec66.png)

Sertakan X-API-KEY di headernya

**Comment by handoyo** [comment]
![image](https://user-images.githubusercontent.com/225439/176993310-739b15d4-8a48-462b-94f1-2ed5b1c3b8b0.png)

Ini hasilnya mas, saya sudah sertakan X-API-KEY di header serta username dan password di body form data.

**Comment by abydahana** [comment]
Pastikan untuk mengaktifkan method POST pada konfigurasi API:
![image](https://user-images.githubusercontent.com/10624446/176995948-18160a14-324b-4574-806e-4bbe010c3f85.png)

**Comment by handoyo** [comment]
Saya sudah aktifkan method POST padahal. Saya akan coba lagi mas.

Makasih.

**Comment by handoyo** [comment]
Malam mas, 

saya masih belum berhasil juga untuk dapetin access tokennya. saya sudah mengaktifkan semua method.

![image](https://user-images.githubusercontent.com/225439/177001462-d3767c45-1bc8-4eb9-94c1-109c5c5f4bda.png)

**Comment by handoyo** [comment]
Pagi mas, 

kira2 apa lagi kemungkinan yang menyebabkan saya tidak bisa manggil POST ya?

makasih.

**Comment by abydahana** [comment]
Saya coba trace dulu. Soalnya pas di saya ndak ada masalah.

Bisa diinfokan versi Aksaranya?

**Comment by handoyo** [comment]
Versi yang dipakai adalah:  4.3.34.1.9

![image](https://user-images.githubusercontent.com/225439/177130924-499c7dc0-ddfe-466c-a5ad-62f275041f68.png)

**Comment by handoyo** [comment]
Siang mas,

apakah ada versi yang saya bisa pakai dulu sambil nunggu mas trace masalah saya yang tidak bisa POST?

Makasih

**Comment by handoyo** [comment]
Siang mas, saya sudah download versi terbaru. namun saya masih tidak bisa mendapatkan access tokennya.

Saya sudah aktifkan semua method, juga sudah sertakan x-api-key di header.

Saya masih mendapatkan error:

`{
    "status": 403,
    "message": "The method you requested is not acceptable (POST)",
    "target": "",
    "redirect": false
}`

**Comment by abydahana** [comment]
> Siang mas, saya sudah download versi terbaru. namun saya masih tidak bisa mendapatkan access tokennya.
> 
> Saya sudah aktifkan semua method, juga sudah sertakan x-api-key di header.
> 
> Saya masih mendapatkan error:
> 
> `{ "status": 403, "message": "The method you requested is not acceptable (POST)", "target": "", "redirect": false }`

Selamat siang.
Mohon maaf atas permasalahannya. Saya akan coba cari tau terlebih dulu beberapa kemungkinannya. Insya Allah dalam waktu dekat ini saya akan rilis versi 4.4.0 dan saya akan pastikan lebih dulu permasalahan masnya bisa teratasi di versi ini.

**Comment by handoyo** [comment]
Baik, terima kasih banyak mas.

**Comment by handoyo** [comment]
Baik mas, saya akan test dulu, saya akan update ke mas hasil testingnya.

**Comment by handoyo** [comment]
Saya sudah coba barusan

![image](https://user-images.githubusercontent.com/225439/177987808-1b4188ab-431a-49ae-b9c9-10d6656a9303.png)

Saya sudah tambahkan username dan password di body form-data, namun muncul error ini.

**Comment by abydahana** [comment]
> Saya sudah coba barusan
> 
> ![image](https://user-images.githubusercontent.com/225439/177987808-1b4188ab-431a-49ae-b9c9-10d6656a9303.png)
> 
> Saya sudah tambahkan username dan password di body form-data, namun muncul error ini.

Gunakan x-www-form-urlencoded

**Comment by abydahana** [comment]
Siap. Silakan informasikan kembali jika ada kendala lain.
