### ISSUE TITLE
error on registration - undefined variable captcha

### ISSUE THREAD

**Issue by Nazamla** [abydahana/aksara#223]
CRITICAL - 2022-07-15 01:53:26 --> Undefined variable: captcha
in APPPATH/Modules/Auth/Views/register.php on line 93.
 1 APPPATH/Modules/Auth/Views/register.php(93): CodeIgniter\Debug\Exceptions->errorHandler()
 2 SYSTEMPATH/View/View.php(213): include('APPPATH/Modules/Auth/Views/register.php')
 3 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH/Common.php(1135): CodeIgniter\View\View->render()
 5 APPPATH/Laboratory/Template.php(573): view()
 6 APPPATH/Laboratory/Core.php(3191): Aksara\Laboratory\Template->build()
 7 APPPATH/Modules/Auth/Controllers/Register.php(122): Aksara\Laboratory\Core->render()
 8 APPPATH/Laboratory/Core.php(255): Aksara\Modules\Auth\Controllers\Register->index()
 9 SYSTEMPATH/CodeIgniter.php(895): Aksara\Laboratory\Core->_remap()
10 SYSTEMPATH/CodeIgniter.php(466): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(106): CodeIgniter\CodeIgniter->run()

**Comment by abydahana** [comment]
Fix under commit #224
