### ISSUE TITLE
Email notifier not working

### ISSUE THREAD

**Issue by ld4709205** [abydahana/aksara#227]
Email notifier appears to be broken; I'm also wondering what these 
fields SMTP email masking and SMTP Sender Masking are for; maybe you can
 provide a sample data for it? Please see the image below. Thank you.

![image (1)](https://user-images.githubusercontent.com/73681680/179918528-58628752-8d83-4e45-bb6a-a76b0b00b044.png)

**Comment by abydahana** [comment]
Please provide the error message you found.

The email and sender masking are used for  the alias of sender. But yet I’m not sure this alias will be worked on common mailserver.

You don’t need to set the email notifier when your app hosted by the server that been support for PHP mailer.

**Comment by ld4709205** [comment]
In the logs and debugbar, there are no errors visible.
![image](https://user-images.githubusercontent.com/73681680/180134883-2e96b89f-361e-442c-9254-a73c855849ef.png)
