### ISSUE TITLE
upgrade boostrap v5

### ISSUE THREAD

**Issue by bupind** [abydahana/aksara#254]
Mas, mohon info untuk:
1. Pagination, total item new mungkin sedikit tersenggol, berdampak tidak menampilkan data sesuai dengan data yang ditampilkan
2. Library dokumen, mungkin bisa menambahkan curlAllowUnsafeSslRequests, supaya non ssl, bisa mengexport file
3. Session login, apakah bisa di set untuk waktu destroy atau jika browser di tutup 
4. Apakah memungkinkan jika merender table bersamaan dengan output lainnya/memanggil fungsi table pada render view bersamaan dengan output lainnya
5. Apakah memungkinkan jika menambah/merubah fungsi pada multiple select, mungkin bisa digunakan sebagai update all, atau deactive all

**Comment by abydahana** [comment]
Kita coba ulik satu-satu, ya.
- Untuk pagination offset sudah dikoreksi #255;
- library dokumen untuk type pdf, excel atau yang mana?

**Comment by abydahana** [comment]
Point 3 sudah ditambahkan di #266
