### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by katvinka** [abydahana/aksara#312]
Hello!

First of all, I would like to say thank you for your development. It turned out to be a great product.

I have been studying Aksara for a couple of days. Identified very big security problems. In particular, any site visitor can create/modify/delete data without authorization and without any groups or privileges.

For example, to add Testimonial, just open the link:

https://demo.aksaracms.com/testimonials/create

In an open form, fill in all the data and send to the server.

Or to update the data:

https://demo.aksaracms.com/testimonials/update?testimonial_id=1

where testimonial_id is the id of the post.

Or delete data:
https://demo.aksaracms.com/testimonials/delete?testimonial_id=3

where testimonial_id is the id of the post.
The same goes for adding a user:
https://demo.aksaracms.com/user/create

Link list:
https://demo.aksaracms.com/pages/create
https://demo.aksaracms.com/testimonials/create
https://demo.aksaracms.com/testimonials/testimonials/update
https://demo.aksaracms.com/testimonials/update?testimonial_id=4
https://demo.aksaracms.com/testimonials/delete?testimonial_id=55
https://demo.aksaracms.com/user/create

There may be more vulnerabilities. This is what was quickly found.
Works both on the demo site and on aksaracms.com

Added on the demo site, an entry in Testimonials and Pages :-) Sorry, I did it for the test.

I recommend fixing it as soon as possible.

p.s.In the next question, I will make a suggestion for improving Aksara.

**Comment by abydahana** [comment]
Hello @katvinka, I’m very appreciate what you found. And yes, as an single fighter developer, I need many suggestions to improve Aksara. I’ll do research ASAP and I hope it’ll be fixed for next update.

**Comment by abydahana** [comment]
Hello @katvinka, please do review the changes #314  I made related to this issue.
