### ISSUE TITLE
seach by column issues

### ISSUE THREAD

**Issue by unnamedCodist** [abydahana/aksara#318]
We are working on searching the list of entries. 
All column filter works as intended, as well as columns that we were successful in configuring. 
However, most of our tables have status fields in them and they are causing ambiguity when we filter by status and they cause the error when they are joined by set_relation(). 
We tried using something like table_name.column_name AS alias_name, this will give error "Unknown column 'alias_name' in 'where clause'". 
Since this did not work, we then used the set_alias() instead, but this is giving us Column 'status' in where clause is ambiguous.

![image](https://user-images.githubusercontent.com/118721357/203002575-35c1c306-2297-4f12-af08-a99b299ee429.png)

![image](https://user-images.githubusercontent.com/118721357/203002707-59e786c6-5031-48b3-b2ef-0018d592fa9e.png)

**Comment by abydahana** [comment]
Fixed #378
