### ISSUE TITLE
Capability to bulk activate Account

### ISSUE THREAD

**Issue by unnamedCodist** [abydahana/aksara#319]
I just noticed that your system has bulk delete feature on the list of users and I would like to have this convenience on activating user accounts by bulk as opposed to activating them individually. Is there a way to use this on set_action()? Thanks
![image](https://user-images.githubusercontent.com/118721357/203712029-e1aca03d-1d84-4e0b-8e06-19182017da8b.png)

**Comment by abydahana** [comment]
You can create a new method or controller to handle the bulk activation / deactivation, and link the method to toolbar ```add_toolbar()``` instead.

https://github.com/abydahana/aksara/blob/25a1972f5a994b6f99647f8fd1a97bbd78d97c22/aksara/Modules/Notifications/Controllers/Notifications.php#L38

https://github.com/abydahana/aksara/blob/25a1972f5a994b6f99647f8fd1a97bbd78d97c22/aksara/Modules/Notifications/Controllers/Send.php#L1-L210
