### ISSUE TITLE
Tipe Data Enum

### ISSUE THREAD

**Issue by tiredbug** [abydahana/aksara#320]
Bagaimana penggunaan tipe data enum pada aksara?
Saya lihat tidak ada di Core.php
Mohon bantuannya..  

Terima kasih

**Comment by abydahana** [comment]
Untuk data enum belum, mas. Mungkin sementara bisa diakali dengan set_field jadi dropdown / radio button. Misal:

set_field(‘nama_field’, ‘dropdown / radio’, array(‘enum_1’ => ‘Enum 1 Label’, ‘enum_2’ => ‘Enum 2 Label’));

**Comment by tiredbug** [comment]
Baik mas... Terima kasih atas pencerahannya..
