### ISSUE TITLE
PDF dengan query pencarian

### ISSUE THREAD

**Issue by tiredbug** [abydahana/aksara#321]
Untuk hasil PDF dan Cetak jika dilakukan query pencarian masih menampilkan seluruh data.
Harusnya hasil PDF dan Cetak ngikuti display query pencarian.
Misal, melakukan pencarian Bandung, di display sudah sesuai menampilkan 2 row, 
sedangkan di PDF dan Cetak masih menampilkan seluruh data yg ada 10000 row.

Mohon pencerahannya,
Terima kasih

**Comment by abydahana** [comment]
Baik, segera saya cek dan lakukan koreksi.

**Comment by abydahana** [comment]
Fixed #358
