### ISSUE TITLE
Use aksara as headless backend

### ISSUE THREAD

**Issue by unnamedCodist** [abydahana/aksara#337]
Is it possible to use Aksara as a headless CMS, which communicates via REST API for frontends to consume (e.g. web frontends made in React, Vue, etc. or mobile clients)?

**Comment by abydahana** [comment]
I haven't tried it yet, but the basic API implementation has added the API Key configuration and also the authorization token to do CRUD. Basically, API communication works as it is already available on the backend web app. You can control related to user privileges as you can get in the user group manager menu.

Please check the API menu for a little guidance.
