### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by soinalastudio** [abydahana/aksara#338]
I installed Aksara on my local server with  PHP 8 and am blocked at the Database configuration stage: "Whoops! Creation of dynamic property App\Controllers\Install::$db is deprecated". What would you propose? Thank you.

**Comment by abydahana** [comment]
Looks like the installation isn't yet compatible with newest CI version. I will update it soon.

**Comment by soinalastudio** [comment]
Yes, I've been able to installed it by changing install.php file but even after installation, it's blocked because of that. Thank you for your effort!

**Comment by abydahana** [comment]
Should be working in newest release
