### ISSUE TITLE
merge_content BUG

### ISSUE THREAD

**Issue by ay4t** [abydahana/aksara#373]
There is a bug when displaying 2 fields or more with the example expression {{ first_name }} {{ last_name }}, it only shows the first expression {{ first_name }}.

![image](https://github.com/abydahana/aksara/assets/87152520/cdde64fc-e187-475a-9ad1-6f9d9d261e83)

![image](https://github.com/abydahana/aksara/assets/87152520/4596c95b-f34c-4b54-8067-3b44c565aefd)

**Comment by abydahana** [comment]
Fixed #375

**Comment by ay4t** [comment]
![image](https://github.com/abydahana/aksara/assets/87152520/c3af4090-02e8-40dc-858a-ab280a6fdc1c)

mantab sekali mas. sudah bisa muncul
