### ISSUE TITLE
Missing css and auth folders, and possibly more

### ISSUE THREAD

**Issue by m4gd1z** [abydahana/aksara#393]
After installing 5.0.3 by downloading the files, extracting them, running 'composer install', then accessing and completing the wizard successfully in the browser, I knew something was wrong because there was no css and the page looked wrong. I checked and found the folder /public/assets/css did not exist. Also, the 'Sign In' link gives a 404 Not Found error. I followed the installation wizard successfully and received no error messages at all while installing. Can I please get some help to try and get Aksara working on my local dev machine. My environment is Mac OS Venture/Apache as module/PHP 8.2/MySQL 8.1.0 - Homebrew. Thank you.

**Comment by abydahana** [comment]
Make sure the rewrite module is enabled under your server environment. To do that, you can update your server configuration:

- Open `/opt/homebrew/etc/httpd/httpd.conf`;
- Make sure the line of "`LoadModule rewrite_module lib/httpd/modules/mod_rewrite.so`" is not commented;
- Change the "`AllowOverride None`" inside the `DocumentRoot` to "`AllowOverride All`";
- Restart apache using ```brew services restart apache2```

Hope that's works.
