### ISSUE TITLE
Missing twig files on the default (front end) theme

### ISSUE THREAD

**Issue by FlavioSuarez** [abydahana/aksara#464]
Hi!

I'm trying Aksara CMS 5.0.6 and love'it!!

Creating a new module and enabling it on a menu on the header don't works. On the sidebar it works ok.
I've found the problem was:
- Parsing error on twig file "themes\default\components\table\boolean.twig"
- Missing the whole folder "themes\default\components\form"

Copying the twig files from "themes\backend\components\table\boolean.twig" and the whole folder "themes\backend\components\form" solved the problem!

Looking forward your project and hoping to be a contributor in the future...
Thanks for your great work!

**Comment by abydahana** [comment]
Hello,
The "Header" placement of the menu management is applied to front end and the "Sidebar" is meant to backoffice (administrative).

About the missing twig file, it's looks like I forgot to add the fallback template for the theme which is have no template components. I will take a look to the case soon.

Thank you for reporting.
