### ISSUE TITLE
Foder Theme

### ISSUE THREAD

**Issue by mdestafadilah** [abydahana/aksara#580]
Halo pak ... folder Themes kenapa sejajar dengan folder Public ya?  Environtment server saya pake nginx, agak tricky pak ... bisa gak folder themes itu didalem Public.

Terima kasih

**Comment by abydahana** [comment]
Kalo tricky-nya di bagian akses file, sudah ada helper tema untuk itu ya, Pak. Struktur asset tema berupa gambar, font, css, js dan lainnya bisa dikelompokkan dalam folder `themes/theme_name/assets/`

Untuk akses filenya bisa menggunakan helper `get_theme_asset()`

Pemanggilannya semisal:
`<script src="<?= get_theme_asset('js/script.js'); ?>"></script>`
`<img src="<?= get_theme_asset('img/deep/path/some-image.jpg'); ?>" alt="..." />`

Dibuat seperti itu supaya jadi standar pengembangan pada ekosistem Aksara.

Adapun kalau semisal cara di atas tidak bekerja pada environment yang Bapak gunakan (NGINX), mungkin bisa melampirkan issue pada bagian mana yang tidak bekerja, atau bisa juga dengan melalukan PR terkait dukungan pada environment yang digunakan.

**Comment by abydahana** [comment]
> > Kalo tricky-nya di bagian akses file, sudah ada helper tema untuk itu ya, Pak. Struktur asset tema berupa gambar, font, css, js dan lainnya bisa dikelompokkan dalam folder `themes/theme_name/assets/`
> > Untuk akses filenya bisa menggunakan helper `get_theme_asset()`
> > Pemanggilannya semisal: `<script src="<?= get_theme_asset('js/script.js'); ?>"></script>` (akan memanggil file /themes/theme_name/assets/js/script.js) `<img src="<?= get_theme_asset('img/deep/path/some-image.jpg'); ?>" alt="..." />` (akan memanggil file /themes/theme_name/assets/img/deep/path/some-img.jpg)
> > Dibuat seperti itu supaya jadi standar pengembangan pada ekosistem Aksara.
> > Adapun kalau semisal cara di atas tidak bekerja pada environment yang Bapak gunakan (NGINX), mungkin bisa melampirkan issue pada bagian mana yang tidak bekerja, atau bisa juga dengan melalukan PR terkait dukungan pada environment yang digunakan.
> 
> Terima kasih pak atas responsenya, baik, coba saya cek ya pak.
> 
> Berarti nanti perubahan update core system ataupun core aksara tidak menyentuh folder `themes` kah pak?
> 
> nanti saya share ya pak, ini saya blm sempet ngulik lagi disisi servernya.

Hanya theme bawaan saja yang teroverride (backend dan default). Seluruh modul dan tema yang dibuat mandiri tidak akan dioverride terkecuali menggunakan struktur folder dan file yang sama.

**Comment by mdestafadilah** [comment]
Halo pak..

```bash
rewrite ^/(.*)$ /index.php/$1/$2 last;
```

![26-09-2024 12-00-00](https://github.com/user-attachments/assets/45a44348-94c4-441e-8589-ebf61638c3ab)

masih belum ketemu pak solusinya, ini kondisi saya *fresh install* aplikasi aksara ya pak, clone dari github.

**Comment by abydahana** [comment]
Bisa pake config ini ya, Pak:
```
server {
    set $public_dir "/path/to/aksaracms/public";

    listen      8081;
    server_name localhost;

    root        $public_dir;
    index       index.php index.html index.htm;

    # Enforce NO www
    if ($host ~* ^www\.(.*)) {
        set $host_without_www $1;
        rewrite ^/(.*)$ $scheme://$host_without_www/$1 permanent;
    }

    # Removes trailing "index" from all controllers
    if ($request_uri ~* index/?$) {
        rewrite ^/(.*)/index/?$ /$1 permanent;
    }

    # Removes trailing slashes (prevents SEO duplicate content issues)
    if (!-d $request_filename) {
        rewrite ^/(.+)/$ /$1 permanent;
    }

    # Removes access to "system" folder, also allows a "System.php" controller
    if ($request_uri ~* ^/system) {
        rewrite ^/(.*)$ /index.php?/$1 last;
        break;
    }

    # Unless the request is for a valid file (image, js, css, etc.), send to bootstrap
    if (!-e $request_filename) {
        rewrite ^/(.*)$ /index.php?/$1 last;
        break;
    }

    # Catch all
    error_page 404 /index.php;

    # Use fastcgi for all php files
    location ~ \.php$ {
        fastcgi_pass    127.0.0.1:9000;
        fastcgi_index   index.php;
        fastcgi_param   SCRIPT_FILENAME $public_dir/$fastcgi_script_name;
        include         fastcgi_params;
    }

    # Deny access to apache .htaccess files
    location ~ /\.ht {
        deny all;
    }
}
```

**Comment by mdestafadilah** [comment]
> # Enforce NO www
>     if ($host ~* ^www\.(.*)) {
>         set $host_without_www $1;
>         rewrite ^/(.*)$ $scheme://$host_without_www/$1 permanent;
>     }
> 
>     # Removes trailing "index" from all controllers
>     if ($request_uri ~* index/?$) {
>         rewrite ^/(.*)/index/?$ /$1 permanent;
>     }
> 
>     # Removes trailing slashes (prevents SEO duplicate content issues)
>     if (!-d $request_filename) {
>         rewrite ^/(.+)/$ /$1 permanent;
>     }
> 
>     # Unless the request is for a valid file (image, js, css, etc.), send to bootstrap
>     if (!-e $request_filename) {
>         rewrite ^/(.*)$ /index.php?/$1 last;
>         break;
>     }
> 
>     # Catch all
>     error_page 404 /index.php;
> 
>     # Use fastcgi for all php files
>     location ~ \.php$ {
>         fastcgi_pass    127.0.0.1:9000;
>         fastcgi_index   index.php;
>         fastcgi_param   SCRIPT_FILENAME $public_dir/$fastcgi_script_name;
>         include         fastcgi_params;
>     }
> 
>     # Deny access to apache .htaccess files
>     location ~ /\.ht {
>         deny all;
>     }

MasyaAllah, mantap kali pak, sudah bisa. terima kasih banyak.
