### ISSUE TITLE
Accents not supported on the public menus labels

### ISSUE THREAD

**Issue by FlavioSuarez** [abydahana/aksara#583]
Hi,

I noticed that accents aren't supported on the public (empty "Group" setting) page's menus labels. You can verify it creating a public Home page menu item with the label 'Notícias'... Not a big issue, really...

TIA and keep the good work!!

**Comment by abydahana** [comment]
Fixed: https://github.com/abydahana/aksara/pull/585

**Comment by FlavioSuarez** [comment]
Great!
I tested it with the main branch version and it works!

Many thanks! Keep the good work!

BTW, in the future I coud help with translation to Spanish and Brazilian portuguese...
BTW 2: What happened to the AksaraCMS home page?
BTW 3: Love it the new demo site. I was expecting to get the same demo site when installing in basic mode (with sample)...

**Comment by abydahana** [comment]
> Great! I tested it with the main branch version and it works!
> 
> Many thanks! Keep the good work!
> 
> BTW, in the future I coud help with translation to Spanish and Brazilian portuguese... BTW 2: What happened to the AksaraCMS home page? BTW 3: Love it the new demo site. I was expecting to get the same demo site when installing in basic mode (with sample)...

1. You can make a PR to submit your translation;
2. The previous server I use was suspended, the price was too high. Now it's migrated to cheaper one and preparing for an update;
3. You should get same results for newest version except for images.

**Comment by FlavioSuarez** [comment]
1. Ah, OK
2. Good to know. Best wishes
3. Yeh, i was talking about the images... :-)

Best regards!
