### ISSUE TITLE
Front end theme customization not applied

### ISSUE THREAD

**Issue by FlavioSuarez** [abydahana/aksara#584]
Hi,

I've customized the front end theme, just changing the 'Header Color Scheme" background to green, but is not working.
Version 5.1.64.5.5

What am I missing?
 
TIA and keep the good work!!

**Comment by abydahana** [comment]
Turn out that I missing the `id="header-wrapper"` in the header section, which is the identity of the customization to be affected.

Please update the `/themes/default/header.php` file and change the first line into:
```
<header role="header" class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top navbar" id="header-wrapper">
```

**Comment by FlavioSuarez** [comment]
I tested with the main branch version and it works!
Many thanks!
