### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by mdestafadilah** [abydahana/aksara#587]
RESTful API

Pak ada contoh pemanfaatan dikodingan aksra?

**Comment by abydahana** [comment]
Bisa menggunakan contoh ini: https://www.postman.com/orange-comet-500353/aksara-laboratory/collection/ia4j5df/aksara-cms

Silakan buat environment baru dengan beberapa variable berikut:
`BASE_URL`: Bagian yang konsisten atau alamat dasar situs web;
`API_KEY`: Kunci API yang dibuat dari halaman API > Layanan;
`USERNAME`: Nama pengguna aplikasi;
`PASSWORD`: Kata sandi untuk pengguna aplikasi.

Otentikasi menggunakan Basic Auth, atau dapat dikirim melalui header menggunakan parameter key `Authorization` dengan value kombinasi antara nama pengguna dan kata sandi yang dipisahkan dengan titik dua (`:`) dan telah dikonversi ke dalam format base64:
Versi clean: `Basic user:password`
Versi base64: `Basic dXNlcjpwYXNzd29yZA==`

**Comment by mdestafadilah** [comment]
Manualbook API Postmannya yang endpoint mana pak?

**Comment by bangil0** [comment]
> Manualbook API Postmannya yang endpoint mana pak?

ada pada https://github.com/abydahana/aksara/tree/main/aksara/Modules/Apis
atau pada <base_url>/public/apis/documentation pada saat setelah instalasi

**Comment by mdestafadilah** [comment]
> > Manualbook API Postmannya yang endpoint mana pak?
> 
> ada pada https://github.com/abydahana/aksara/tree/main/aksara/Modules/Apis atau pada <base_url>/public/apis/documentation pada saat setelah instalasi

Alhamdulillah, mantap pak, terima kasih ya, saya close.
