### ISSUE TITLE
soft delete method becomes the default and forcing the user to change the password

### ISSUE THREAD

**Issue by bangil0** [abydahana/aksara#627]
Is it possible to modify the direct delete method to a soft delete method?
maybe it could be a note,
Thank you very much.

**Comment by abydahana** [comment]
Can be implemented by adding `before_delete()` function in the controller.
Example:

```php
public function before_delete()
{
    $this->model->update(
        $this->_table,
        [
            'deleted' => 1
        ],
        [
            'id' => service('request')->getGet('id') ?? 0
        ]
    );

    return throw_exception(301, 'The selected data was successfully deleted.', go_to(null, ['id' => null]));
}
```

**Comment by bangil0** [comment]
how to force users to change their passwords maybe once every 3 months ?
Thank you very much.

**Comment by abydahana** [comment]
> how to force users to change their passwords maybe once every 3 months ? Thank you very much.

Could be done with these workflow:
1. Create new table to store password update timestamp;
2. Fork `/aksara/Modules/Administrative/Controllers/Account/Edit.php` to `/modules/Administrative/Controllers/Account/Edit.php`;
3. Fork `/aksara/Modules/Dashboard/Controllers/Dashboard.php` to `modules/Dashboard/Controllers/Dashboard.php`;
4. Edit `/modules/Administrative/Controllers/Account/Edit.php` file and add an update query to `after_update()` function to update the record of point 1;
5. Edit `modules/Dashboard/Controllers/Dashboard.php` file and add the query to the beginning of `index` function to check the timestamp from table point 1;
6. Redirect to `administrative/account/edit` if the timestamp is more than 3 months.
